routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FilmController;
use App\Http\Controllers\FilmActionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FilmController::class, 'index']);
Route::get('/published-films', [FilmActionController::class, 'index'])->name('published');

Route::resource('film', FilmController::class);

app/Models/Film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'films';
    protected $fillable = ['title','img'];

    public function genres()
    {
        return $this->belongsToMany(Genre::class);
    }

    public static function updateData(int $id, mixed $title)
    {
        return Film::where('id', $id)
            ->update(['title' => $title]);
    }


    public static function changeStatus($id)
    {
        $status = Film::find($id);
        if ($status->status === 'inactive') {
            $status->status = 'active';
            $status->save();
        } else {
            $status->status = 'inactive';
            $status->save();
        }
    }
}

app/Models/FilmGenre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FilmGenre extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'film_genre';
    protected $fillable = ['film_id', 'genre_id'];
}

app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'genres';

    public function filmes(){
        return $this->belongsToMany(Film::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FilmActionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Film;
use App\Models\Genre;
use Illuminate\Http\Request;

class FilmActionController extends Controller
{
    public function index()
    {
        return view('film.index', [
            'films' => Film::where('status', 'active')->paginate(8),
            'genres' => Genre::all()
        ]);
    }
}

app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use App\Models\Film;
use App\Models\FilmGenre;
use App\Models\Genre;
use Illuminate\Http\Request;
use App\Http\Requests\FilmRequest;

class FilmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('film.index', [
            'films' => Film::paginate(8),
            'genres' => Genre::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('film.create', [
            'genres' => Genre::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(FilmRequest $request)
    {
        $path = $request->file('img')->store('film_img', 'public');

        Film::create(
            [
                'title' => $request->title,
                'img' => $path
            ]
        );
        FilmGenre::create([
            'film_id' => Film::max('id'),
            'genre_id' => $request->genre_id
        ]);
        return redirect(route('film.index'))->with('message', 'Film "' . $request->title . '", added.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        Film::changeStatus($id);
        return redirect(route('film.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('film.edit', [
            'film' => Film::find($id),
            'genres' => Genre::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(FilmRequest $request, $id)
    {
        Film::updateData($id, $request->title);
        return redirect(route('film.index'))->with('message', 'Film "' . $request->title . '", updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $title = Film::find($id)->title;
        $FilmGenreId = FilmGenre::where('film_id', $id)->first()->id;

        //удаление записи с таблици film_genre
        FilmGenre::destroy($FilmGenreId);

        // удаление записи с таблици films
        Film::destroy($id);

        return redirect(route('film.index'))->with('message', 'Film "' . $title . '", deleted.');
    }
}

app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class GenreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/film/create.blade.php
@extends('main')
@section('content')

    <div class="py-5 text-center container">

        <h2 class="fw-light">Create new film</h2>

        <form enctype="multipart/form-data" method="post" action="{{ route('film.store') }}">
            @csrf
            <div class="card-body">
                {{--title--}}
                <div class="form-group text-start mb-4">
                    <label class="" for="exampleInputTitle">Title</label>
                    <input name="title" type="text" class="form-control @error('title') is-invalid @enderror"
                           value="{{ old('title') }}"
                           id="exampleInputEmail1" placeholder="Enter title">
                    @error('title')
                    <span class="alert-danger">{{ $message }}</span>
                    @enderror
                </div>

                {{--genre--}}
                <div class="form-group text-start mb-4">
                    <label for="exampleInputCategory">Genre</label>
                    <select name="genre_id" id="exampleInputCategory"
                            class="form-control @error('genre_id') is-invalid @enderror">
                        <option>Please select genre</option>

                        @foreach($genres as $genre)
                            <option @if(old('genre_id') && old('genre_id') == $genre->id)
                                    selected
                                    @endif
                                    value="{{ $genre->id }}">{{ $genre->title }}
                            </option>
                        @endforeach
                    </select>
                    @error('genre_id')
                    <span class="alert-danger">{{ $message }}</span>
                    @enderror
                </div>

                {{--imgage--}}
                <div class="form-group mt-4 mb-4 text-start  ">
                    <label for="exampleInputFile">Film image</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" name="img"
                                   class="custom-file-input @error('img') is-invalid @enderror"
                                   id="exampleInputFile">
                        </div>
                    </div>
                </div>
                @error('img')
                <span class="alert-danger">{{ $message }}</span>
                @enderror
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>

    </div>

@endsection()

resources/views/film/edit.blade.php
@extends('main')
@section('content')

    <div class="py-5 text-center container">

        <h2 class="fw-light">Edit film</h2>
        <form enctype="multipart/form-data" method="post" action="{{ route('film.update',['film'=>$film->id]) }}">
            @csrf
            @method('put')
            <div class="card-body">
                {{--title--}}
                <div class="form-group text-start mb-4">
                    <label class="" for="exampleInputTitle">Title</label>
                    <input name="title" type="text" class="form-control @error('title') is-invalid @enderror"
                           value="{{ old('title') ?? $film->title}}"
                           id="exampleInputEmail1" placeholder="Enter title">
                    @error('title')
                    <span class="alert-danger">{{ $message }}</span>
                    @enderror
                </div>

                {{--genre--}}
                <div class="form-group text-start mb-4">
                    <label for="exampleInputCategory">Genre</label>
                    <select name="genre_id" id="exampleInputCategory"
                            class="form-control @error('genre_id') is-invalid @enderror">
                        <option>Please select genre</option>

                        @foreach($genres as $genre)
                            <option @if(old('genre_id') && old('genre_id') == $genre->id)
                                    selected
                                    @endif
                                    {{--                                    @if((old('genre_id') && old('genre_id') == $genre->id) || $genre->id==$product->category_id)--}}
                                    @if((old('genre_id') && old('genre_id') == $genre->id) )
                                    selected
                                    @endif
                                    value="{{ $genre->id }}">{{ $genre->title }}
                            </option>
                        @endforeach
                    </select>
                    @error('genre_id')
                    <span class="alert-danger">{{ $message }}</span>
                    @enderror
                </div>

                {{--image--}}
                <div class="form-group mt-4 mb-4 text-start">

                    <label for="exampleInputFile"></label>
                    <img style="height: 100px" class="img-thumbnail" src="{{ asset('/storage/'.$film->img)}}"alt="poster">

                    <div class="input-group">


                        <div class="custom-file">
                            <input type="file" name="img"
                                   class="custom-file-input @error('img') is-invalid @enderror"
                                   id="exampleInputFile">

                        </div>
                    </div>
                </div>
                @error('img')
                <span class="alert-danger">{{ $message }}</span>
                @enderror
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>

    </div>

@endsection()

resources/views/film/index.blade.php
@extends('main')

@section('content')

    <div class="container pt-4 ">
        @if (session('message'))
            <div class="toast-body bg-secondary text-white">
                {{ session('message') }}
            </div>
        @endif
        <div class="row d-flex">
            <div class="col-3">
                @foreach($genres as $genre)
                    <p><a href="#">{{ $genre->title }}</a></p>
                @endforeach

                <a href="{{ route('published') }}"
                   class="btn btn-outline-warning ml-3 mb-2">only published films</a>
                <p>
                    <a href="{{ route('film.index') }}"
                       class="btn btn-outline-success ml-3 mb-2">main page</a>
                </p>
            </div>
            <div class="col">
                <div class="row">
                    @foreach($films as $film)
                        <div class="col-3">
                            <p>{{ $film->title }}</p>

                            <div class="img-fluid">
                                @if($film->img)
                                    <img class="img-fluid" src="{{ asset('/storage/'.$film->img)}}" alt="poster">
                                @else
                                    <img class="img-fluid" src="/storage/film_img/def.jpg"
                                         alt="poster">
                                @endif
                            </div>

                            {{-- активны/не активный --}}
                            <form method="get"
                                  action="{{ route('film.show',['film'=>$film->id]) }}"
                                  role="form"
                                  class="bd-highlight mb-2">
                                @csrf
                                @if( $film->status == 'active')
                                    <input class="mt-2 btn btn-block btn-outline-success btn-sm"
                                           type="submit"
                                           value="{{ $film->status }}">
                                @else
                                    <input class="mt-2 btn btn-block btn-outline-secondary btn-sm"
                                           type="submit"
                                           value="{{ $film->status }}">
                                @endif
                            </form>
                            {{--------------------}}

                            <a href="{{ route('film.edit', ['film'=>$film->id]) }}"
                               class="btn btn-outline-warning ml-3 mb-2">Edit</a>
                            <form
                                action="{{ route('film.destroy', ['film'=>$film->id]) }}"
                                method="post" class="mb-4">
                                @csrf
                                @method('delete')
                                <button type="submit" title="delete forever" type="button"
                                        class="btn btn-outline-danger ml-3">Delete
                                </button>
                            </form>
                        </div>
                    @endforeach
                </div>
                <a href="{{ route('film.create') }}" class="btn btn-primary ml-3 mb-4">Сreate a poster</a>

                {{ $films->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Styles -->
    <style>
        /*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
        html {
            line-height: 1.15;
            -webkit-text-size-adjust: 100%
        }

        body {
            margin: 0
        }

        a {
            background-color: transparent
        }

        [hidden] {
            display: none
        }

        html {
            font-family: system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji;
            line-height: 1.5
        }

        *, :after, :before {
            box-sizing: border-box;
            border: 0 solid #e2e8f0
        }

        a {
            color: inherit;
            text-decoration: inherit
        }

        svg, video {
            display: block;
            vertical-align: middle
        }

        video {
            max-width: 100%;
            height: auto
        }

        .bg-white {
            --bg-opacity: 1;
            background-color: #fff;
            background-color: rgba(255, 255, 255, var(--bg-opacity))
        }

        .bg-gray-100 {
            --bg-opacity: 1;
            background-color: #f7fafc;
            background-color: rgba(247, 250, 252, var(--bg-opacity))
        }

        .border-gray-200 {
            --border-opacity: 1;
            border-color: #edf2f7;
            border-color: rgba(237, 242, 247, var(--border-opacity))
        }

        .border-t {
            border-top-width: 1px
        }

        .flex {
            display: flex
        }

        .grid {
            display: grid
        }

        .hidden {
            display: none
        }

        .items-center {
            align-items: center
        }

        .justify-center {
            justify-content: center
        }

        .font-semibold {
            font-weight: 600
        }

        .h-5 {
            height: 1.25rem
        }

        .h-8 {
            height: 2rem
        }

        .h-16 {
            height: 4rem
        }

        .text-sm {
            font-size: .875rem
        }

        .text-lg {
            font-size: 1.125rem
        }

        .leading-7 {
            line-height: 1.75rem
        }

        .mx-auto {
            margin-left: auto;
            margin-right: auto
        }

        .ml-1 {
            margin-left: .25rem
        }

        .mt-2 {
            margin-top: .5rem
        }

        .mr-2 {
            margin-right: .5rem
        }

        .ml-2 {
            margin-left: .5rem
        }

        .mt-4 {
            margin-top: 1rem
        }

        .ml-4 {
            margin-left: 1rem
        }

        .mt-8 {
            margin-top: 2rem
        }

        .ml-12 {
            margin-left: 3rem
        }

        .-mt-px {
            margin-top: -1px
        }

        .max-w-6xl {
            max-width: 72rem
        }

        .min-h-screen {
            min-height: 100vh
        }

        .overflow-hidden {
            overflow: hidden
        }

        .p-6 {
            padding: 1.5rem
        }

        .py-4 {
            padding-top: 1rem;
            padding-bottom: 1rem
        }

        .px-6 {
            padding-left: 1.5rem;
            padding-right: 1.5rem
        }

        .pt-8 {
            padding-top: 2rem
        }

        .fixed {
            position: fixed
        }

        .relative {
            position: relative
        }

        .top-0 {
            top: 0
        }

        .right-0 {
            right: 0
        }

        .shadow {
            box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06)
        }

        .text-center {
            text-align: center
        }

        .text-gray-200 {
            --text-opacity: 1;
            color: #edf2f7;
            color: rgba(237, 242, 247, var(--text-opacity))
        }

        .text-gray-300 {
            --text-opacity: 1;
            color: #e2e8f0;
            color: rgba(226, 232, 240, var(--text-opacity))
        }

        .text-gray-400 {
            --text-opacity: 1;
            color: #cbd5e0;
            color: rgba(203, 213, 224, var(--text-opacity))
        }

        .text-gray-500 {
            --text-opacity: 1;
            color: #a0aec0;
            color: rgba(160, 174, 192, var(--text-opacity))
        }

        .text-gray-600 {
            --text-opacity: 1;
            color: #718096;
            color: rgba(113, 128, 150, var(--text-opacity))
        }

        .text-gray-700 {
            --text-opacity: 1;
            color: #4a5568;
            color: rgba(74, 85, 104, var(--text-opacity))
        }

        .text-gray-900 {
            --text-opacity: 1;
            color: #1a202c;
            color: rgba(26, 32, 44, var(--text-opacity))
        }

        .underline {
            text-decoration: underline
        }

        .antialiased {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale
        }

        .w-5 {
            width: 1.25rem
        }

        .w-8 {
            width: 2rem
        }

        .w-auto {
            width: auto
        }

        .grid-cols-1 {
            grid-template-columns:repeat(1, minmax(0, 1fr))
        }

        @media (min-width: 640px) {
            .sm\:rounded-lg {
                border-radius: .5rem
            }

            .sm\:block {
                display: block
            }

            .sm\:items-center {
                align-items: center
            }

            .sm\:justify-start {
                justify-content: flex-start
            }

            .sm\:justify-between {
                justify-content: space-between
            }

            .sm\:h-20 {
                height: 5rem
            }

            .sm\:ml-0 {
                margin-left: 0
            }

            .sm\:px-6 {
                padding-left: 1.5rem;
                padding-right: 1.5rem
            }

            .sm\:pt-0 {
                padding-top: 0
            }

            .sm\:text-left {
                text-align: left
            }

            .sm\:text-right {
                text-align: right
            }
        }

        @media (min-width: 768px) {
            .md\:border-t-0 {
                border-top-width: 0
            }

            .md\:border-l {
                border-left-width: 1px
            }

            .md\:grid-cols-2 {
                grid-template-columns:repeat(2, minmax(0, 1fr))
            }
        }

        @media (min-width: 1024px) {
            .lg\:px-8 {
                padding-left: 2rem;
                padding-right: 2rem
            }
        }

        @media (prefers-color-scheme: dark) {
            .dark\:bg-gray-800 {
                --bg-opacity: 1;
                background-color: #2d3748;
                background-color: rgba(45, 55, 72, var(--bg-opacity))
            }

            .dark\:bg-gray-900 {
                --bg-opacity: 1;
                background-color: #1a202c;
                background-color: rgba(26, 32, 44, var(--bg-opacity))
            }

            .dark\:border-gray-700 {
                --border-opacity: 1;
                border-color: #4a5568;
                border-color: rgba(74, 85, 104, var(--border-opacity))
            }

            .dark\:text-white {
                --text-opacity: 1;
                color: #fff;
                color: rgba(255, 255, 255, var(--text-opacity))
            }

            .dark\:text-gray-400 {
                --text-opacity: 1;
                color: #cbd5e0;
                color: rgba(203, 213, 224, var(--text-opacity))
            }

            .dark\:text-gray-500 {
                --tw-text-opacity: 1;
                color: #6b7280;
                color: rgba(107, 114, 128, var(--tw-text-opacity))
            }
        }
    </style>

    <style>
        body {
            font-family: 'Nunito', sans-serif;
        }
    </style>
</head>
<body class="antialiased">
<h1 class="text-center mt-4" >Test-task</h1>
@yield('content')
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>